### PR TITLE
fix: ensure git signatures are not present

### PR DESCRIPTION
**Pull request by adam-moss**
Currently an empty changeset is produced if the git configuration has `log.showSignature` set to `true`.  This change ensure we set it to `false` to allow commit header parsing to function correctly.

Further information can be found in
- https://github.com/conventional-changelog/conventional-changelog/issues/213
- https://github.com/conventional-changelog/conventional-changelog/pull/671

Signed-off-by: Adam Moss <2951486+adam-moss@users.noreply.github.com>

### CODE REVIEW

**Comment by adam-moss** [comment]
@TimothyJones any chance of a review of this please?

**Comment by TimothyJones** [comment]
Thanks for the reminder! Much appreciated.

Just to confirm, this fixes an issue where the changelog would incorrectly be empty if there were signed commits?

I'm not too familiar with git signatures - Is it possible to add a test, or would it be too clumsy to create a signed commit?

**Comment by adam-moss** [comment]
Hi,

So this issue is more if the `log.showSignature` setting in the git config is true.

When it is the `git log` will show the signature before the commit, so the change log is always empty because the signature is incorrectly put in as the commit message header, resulting in it never matching against the conventional `type`

**Comment by TimothyJones** [comment]
Aha! That makes sense. I’m not at a computer now, but I will merge and release this tomorrow.

**Comment by TimothyJones** [comment]
Released as 11.1.0, please let me know if there are any issues. Thanks again for the PR!

**Pull request merged**
