### PR TITLE
feat: Add OpenAPI version support

### PR DESCRIPTION
**Pull request by ixuz**
This PR just adds another updater type `openapi.js` for OpenAPI specification files.

### CODE REVIEW

**Comment by ixuz** [comment]
@TimothyJones Please have a look at this one.  Cheers and thank you for maintaining this repo! :+1:

**Comment by ixuz** [comment]
@TimothyJones I've aligned this implementation to the YAML updater that already exists.

**Comment by TimothyJones** [comment]
Looks good to me - although, for some reason this change rewrites the whole README - is it possible to not do that?

**Comment by ixuz** [comment]
> Looks good to me - although, for some reason this change rewrites the whole README - is it possible to not do that?

Fixed! I don't know what that happened. 😄

**Comment by TimothyJones** [comment]
Releasing as [12.4.0](https://github.com/absolute-version/commit-and-tag-version/releases/tag/v12.4.0). Thanks again!

**Pull request merged**
