### PR TITLE
fix: preserve frontmatter when updating changelog 

### PR DESCRIPTION
**Pull request by TimKnight-DWP**
fixes: #106

### CODE REVIEW

**Comment by TimKnight-DWP** [comment]
I'll have a look at these failing tests

**Comment by TimothyJones** [comment]
Thanks! Sorry about the lint settings. Every time I work on this, I'm tempted to replace the format rules with default prettier settings, but I didn't really want to fork it and then go "ok here are all _my_ opinions", you know? :)

You may also want to merge in master again - speaking of lint settings, I realised that some of the tests weren't actually running, due to dangling promises. So I updated those with some defaults designed to prevent tests that don't do what is expected.

I've enabled the "update branch" button to make this easy.

**Comment by TimKnight-DWP** [comment]
To be fair, I think moving to some Default Prettier settings would make sense, at least they are a default set of opinions used across tech 😄

**Comment by TimothyJones** [comment]
Good point, prettier has definitely won out. I'm convinced.

I reckon I'll do it after this, #99 and #109 have landed - I don't want to stamp on the toes of people currently in the middle of contributing.

**Comment by TimKnight-DWP** [comment]
Awesome.

**Comment by TimKnight-DWP** [comment]
Could've sworn I had run "fix" before pushing, but hey ho.

All done now

**Comment by TimothyJones** [comment]
Thanks again! Releasing as 12.0.0 (since I also dropped node 14 and 16)

**Pull request merged**
