### PR TITLE
feat: support customize `npmPublishHint`

### PR DESCRIPTION
**Pull request by bytemain**
I'm using some npm client that not npm.

so I want it directly show `yarn publish`

### CODE REVIEW

**Comment by TimothyJones** [comment]
Hmm. Is it always `publish` for custom npm commands?

**Comment by bytemain** [comment]
Yes, I'm just using `yarn` as an example. In our team, we can only use specific NPM Client to publish package.

**Comment by bytemain** [comment]
Oh, I see what you mean. You mean let the user customize the whole publish command?

**Comment by TimothyJones** [comment]
Yeah. I'm not sure if there is a way to let the hint be easily parameterisable without running into potential issues (like the custom client not supporting `publish`). The git command isn't always correct either.

I think generally if the hint is not correct, then you probably already know what it means and how to translate it. However, I do take your point that it would be nice if the hint were correct.

It might be better to either:

1) Allow the entire hint to be customised
or
2) For the common cases (`npm` and `yarn`) we could look for the respective lock file and hint accordingly.

**Comment by TimothyJones** [comment]
What do you think?

**Comment by bytemain** [comment]
We can use https://www.npmjs.com/package/detect-package-manager to detect current directory package manager.

And we can provide two options:
- npmClientName
- npmClientPublishCommand

How about this? then most user can only change the `npmClientName`.

**Comment by TimothyJones** [comment]
I’m a fan of keeping the api surface small if possible (this helps reduce long term maintenance effort)- what about just detecting the package manager and printing an appropriate message?If you feel strongly that it should be configurable, I reckon the whole “here’s how you publish” message should be one parameter, in order to cover the most bases and extend the API options surface the least.Thanks for putting tests in the PR, btw. Much appreciated!Sent from my mobileOn 20 Feb 2023, at 4:34 pm, Artin ***@***.***> wrote:﻿
We can use https://www.npmjs.com/package/detect-package-manager to detect current directory package manager.
And we can provide two options:

npmClientName
npmClientPublishCommand

How about this? then most user can only change the npmClientName.

**Comment by bytemain** [comment]
for [If you feel strongly that it should be configurable], my answer is yes.
because our package manager is a private package, it's an `npm` based manager, but with a changed name.

so we will provide an option:
- npmPublishHint

If the user does not set this configuration, we will automatically detect package manager and construt it to`${clientName} publish`

**Comment by bytemain** [comment]
@TimothyJones hello, I have implemented the relevant functions, pls have a look, thank you~

**Comment by TimothyJones** [comment]
Apologies! I thought I had reviewed and merged this. I'll get it out now.

Thanks again!

**Review by TimothyJones — APPROVED** [review]

**Pull request merged**
