### PR TITLE
feat(updater): add .csproj file support

### PR DESCRIPTION
**Pull request by FlorianArnould**
Just a new internal `updater` implementation to support the .NET `.csproj`

### CODE REVIEW

**Comment by TimothyJones** [comment]
This is awesome, thanks! Could you add this capability into the readme too?

**Comment by FlorianArnould** [comment]
I will try to check this tomorrow.
Do I just add a section about .NET and .csproj files like the `gradle-support-javakotlin` one ?

**Comment by TimothyJones** [comment]
Sounds good!

**Comment by FlorianArnould** [comment]
That's it.  
I also rebased on `master`.
Let me know if there is something else.

**Comment by TimothyJones** [comment]
Released in 11.3.0. Thanks again!

**Pull request merged**
